travis:
  secure:
    BINSTAR_TOKEN: BQMAzNO0ybMZMkItMFbJYHBdO+e95rUzRTbsBRsb5fkAKYwlyPX3gjr0kZ1+y6cKRfYstThKM1pt4RiGYfdOA9s2fb8Zaznd1tiu4EYerCtfymr1J//CHaByDK6NxkdkC0VBfLrBsD8iSvstXFQy3rdAX9X7SO+BN/+HhOOEP94OXjgmMPBXXHQmWoCtdfpX7Bz6Y3uLYE7koFkTpLosk7bq89bSjtS4eVjfNpK5m6UCmjRWPragUeiSFvH601oy+OpyOp8UmrNLBezEvlEOOCGcr6rr+OEqTkbZ6gyVLwTgaReE4acMtUluuTmLtOtsUXW0J3mzfqSb4pFK+HbRkCR/x65MbL24N9TYjzDN/aMOn0nZM9nLSarrdJ2Dfpsq+TSpMcEFtW4zKSHVExJWwjRCOm2dMDpp2D698H90eiIBnl9au1aJQepJyMKxU2noCvbUAX5aO+VKZjIeioOUubxDLhquSe0VyFASpyns/iDDrS9IOdhL5zuUP3YTDKeB8wkNmVUsnt/b8YyToPgWyKDoT8t19QcbPt2KoJBkipe3xucl0CW56liZHFDoRQKEo0KUS5xZZ+krlAMlVHveJlYS/bJJ3nI37yj8Oir2bjfK406o9Y5we+mUxpUnY39KJrXAfMyc0klHo920MI+Ep4/R8lDJs5KP/CBIwgw1Cdk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
